using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
namespace KingdomAdvisor
{
    // 显示适配器：领域标识、原生数据、旧配置键保持不变。
    public static class Localization
    {
        public static bool English {get;set;}=true;
        private static readonly Dictionary<string,string> translations=new Dictionary<string,string>(StringComparer.Ordinal)
        {
            { "特殊改造", "Special conversion" },
            { "乘员条件", "Passenger requirement" },
            { "需要带上", "Requires passenger: " },
            { "需要带上号角隐士。", "Requires the horn hermit as a passenger." },
            { "巨蛇／奥林匹斯终局", "Serpent / Olympus finale" },
            { "奥林匹斯任务中的巨蛇会制造贪婪怪威胁，并在终局阻挡通往奥林匹斯的道路。", "The serpent creates Greed threats during Olympus quests and blocks the path to Olympus in the finale." },
            { "终局需完成木马部件并集结人员；不能套用普通悬崖炸弹流程。", "Complete the Trojan horse parts and assemble its crew for the finale; ordinary cliff bomb rules do not apply." },
            { "赫淮斯托斯任务", "Hephaestus quest" },
            { "奥林匹斯任务：取回金锤，清除任务岛的敌方据点并重建神祇锻造设施，获得赫淮斯托斯之锤。", "Olympus quest: recover the golden hammer, clear the quest island stronghold, and rebuild the divine forge to obtain Hephaestus' hammer." },
            { "神锤可召出铁砧，为附近部队的武器赋予火焰；此任务设施不同于普通骑士装备锻造。", "The hammer summons an anvil that grants nearby troops flaming weapons; this quest forge differs from ordinary knight equipment shops." },
            { "珀耳塞福涅任务", "Persephone quest" },
            { "奥林匹斯雅典娜任务：解救珀耳塞福涅，带她到永冻之树，协助种出金苹果。", "Athena's Olympus quest: free Persephone and carry her to the permafrost tree to grow the golden apple." },
            { "她是任务乘员，不是将普通农舍改造成马厩的隐士；完成金苹果任务可获得雅典娜之盾。", "She is a quest passenger, not the stable hermit; completing the golden apple quest grants Athena's shield." },
            { "阿耳忒弥斯任务", "Artemis quest" },
            { "奥林匹斯任务：建造捕获笼，骑雄鹿把金鹿引入笼中，获得阿耳忒弥斯之弓。", "Olympus quest: build the cage and ride a stag to lure the golden stag into it, obtaining Artemis' bow." },
            { "神弓向附近敌人发射追踪箭；与普通弓箭手工具不同。", "The divine bow fires homing arrows at nearby enemies; it differs from ordinary archer tools." },
            { "雷神谜题／神锤", "Thor's puzzle / hammer" },
            { "北欧符文谜题，按岛上的线索调整符文柱，完成后可取得雷神之锤。", "A Norse rune puzzle: set the pillars according to the island's clues to obtain Thor's hammer." },
            { "装备后可召唤雷击攻击附近敌人；君主能力与坐骑能力是不同操作。", "Once equipped, it calls lightning against nearby enemies; ruler and mount abilities use separate controls." },
            { "海拉献祭／幽灵部队", "Hel's offering / ghost squad" },
            { "北欧献祭谜题，需要部队献出装备；完成后获得可召唤幽灵突击队的海拉战利品。", "A Norse offering puzzle where troops surrender equipment; completion grants Hel's trophy to summon a ghostly raiding squad." },
            { "需有符合条件的侍从和持盾弓手；献出装备后人员需要重新装备。", "Requires an eligible squire and shielded archers; subjects need re-equipping after surrendering their weapons." },
            { "解锁与换乘费用以当前对象为准。", "Unlocking and switching costs come from the current object." },
            { "可解锁坐骑：", "Available mounts: " },
            { "解锁点", " unlock site" },
            { "熊", "Bear" },
            { "奔跑时向前扑击，可攻击贪婪怪和野生动物；在森林中移动较快。", "Pounces forward while galloping, attacking Greed and wildlife; moves faster in forests." },
            { "在草地进食恢复；连续攻击会使其疲劳，注意退路。", "Feeds on grass; repeated attacks cause fatigue, so keep an escape route." },
            { "雄鹿", "Stag" },
            { "可吸引野鹿跟随，帮助把猎物引向弓箭手；在森林中奔跑较快。", "Attracts wild deer to follow, bringing prey towards archers; runs faster in forests." },
            { "在草地进食恢复；奥林匹斯中也用于引导任务牡鹿。", "Feeds on grass; also leads the quest stag in Olympus." },
            { "战马", "Warhorse" },
            { "发动能力可为附近臣民提供临时防护，帮助部队承受攻击。", "Its ability temporarily protects nearby subjects, helping troops withstand attacks." },
            { "在草地进食恢复；防护有持续时间和冷却。", "Feeds on grass; protection has a duration and cooldown." },
            { "蜥蜴", "Lizard" },
            { "向前喷出火焰，在地面留下火焰伤害区域。", "Spits fire forward, leaving a damaging trail on the ground." },
            { "靠日光休息恢复饱食；夜间和冬季应提前规划耐力。", "Basks in sunlight for its well-fed bonus; plan stamina before night and winter." },
            { "独角兽", "Unicorn" },
            { "在草地进食后可产出金币，提供额外收入。", "Can produce coins after grazing, providing extra income." },
            { "产币有冷却；冬季缺少草地会限制进食与收入。", "Coin production has a cooldown; winter grass shortages limit feeding and income." },
            { "耐力马", "Draft horse" },
            { "拥有较长的奔跑耐力，没有主动攻击能力。", "Has extended galloping stamina and no active attack ability." },
            { "在草地进食恢复，适合长距离往返。", "Feeds on grass; useful for long journeys." },
            { "速度马", "Fast horse" },
            { "马匹的速度变体，没有主动攻击能力。", "A speed-focused horse variant with no active attack ability." },
            { "速度与耐力取舍不同于起始马；在草地进食恢复。", "Its speed and stamina tradeoff differs from the starter horse; feeds on grass." },
            { "疾驰马", "Burst horse" },
            { "马匹的疾驰变体，没有主动攻击能力。", "A galloping-focused horse variant with no active attack ability." },
            { "奔跑速度与耐力取舍不同；在草地进食恢复。", "Has a different speed and stamina tradeoff; feeds on grass." },
            { "亡灵马", "Undead horse" },
            { "死寂之地的起始马，提供移动能力，没有主动攻击能力。", "The starter horse in Dead Lands; provides movement without an active attack ability." },
            { "两位君主中的亡灵马仍需在草地进食；不能套用新大陆的无限耐力。", "In Two Crowns it still grazes; do not apply the unlimited stamina from New Lands." },
            { "巨狼", "Wolf" },
            { "可发动连续扑击攻击贪婪怪；北欧变体还可为附近臣民提供防护。", "Can pounce repeatedly at Greed; the Norse variant also protects nearby subjects." },
            { "在林外有月光时嚎叫恢复饱食；留意攻击次数和冷却。", "Howls under moonlight outside forests for its well-fed bonus; watch charges and cooldown." },
            { "驯鹿", "Reindeer" },
            { "北欧的驯鹿具有雄鹿式引鹿能力，适合森林探索与引导猎物。", "The Norse reindeer lures deer like the stag, helping forest exploration and hunting." },
            { "在草地进食恢复；节日变体的雪橇交互只适用于对应活动。", "Feeds on grass; sleigh interactions belong to the relevant seasonal event." },
            { "加米金", "Gamigin" },
            { "死寂之地的恶魔坐骑，可向前冲撞，伤害并击退目标。", "A demonic Dead Lands mount that charges forward to damage and push back targets." },
            { "可在任意地形进食；冲撞不能保证击杀强敌。", "Can feed on any terrain; charging does not guarantee a kill against stronger foes." },
            { "魔像", "Golem" },
            { "站定后可召出树根屏障，阻挡并拖延贪婪怪。", "Can summon a root barrier while stationary to block and delay Greed." },
            { "在草地进食恢复；新屏障达到数量限制后会替换旧屏障。", "Feeds on grass; new barriers replace the oldest once the limit is reached." },
            { "甲虫", "Beetle" },
            { "向身后放置幼虫陷阱，可消灭经过的小型贪婪怪。", "Places a larva trap behind it that kills passing small greedlings." },
            { "陷阱不会消灭巨型怪或飞行怪；在草地进食恢复。", "Traps do not kill breeders or floaters; feeds on grass." },
            { "八足神马", "Sleipnir" },
            { "北欧坐骑，可冲锋击退敌人，并在身后留下火焰轨迹。", "A Norse mount that charges to push back enemies and leaves a fire trail." },
            { "在草地进食恢复；留意冲锋冷却及地面火焰。", "Feeds on grass; watch the charge cooldown and fire on the ground." },
            { "猫拉战车", "Cat chariot" },
            { "北欧坐骑，可短时高速冲刺，并让附近的猫跟随。", "A Norse mount with a brief speed burst that also attracts nearby cats." },
            { "可在任意地形进食；冲刺用于赶路，不是直接伤害攻击。", "Can feed on any terrain; its dash is for travel, not a damaging attack." },
            { "水马", "Water horse" },
            { "暖季释放水波击退敌人并灭火；冬季改为召唤冰墙。", "Releases waves that repel enemies and extinguish fire in warmer seasons; summons ice walls in winter." },
            { "可在任意地形吸水恢复；冰墙有数量限制。", "Can absorb water on any terrain; ice walls have a quantity limit." },
            { "黄金野猪", "Golden boar" },
            { "主动拱地可恢复耐力，有机会挖出金币，并强化附近农田。", "Rooting actively restores stamina, may uncover coins, and buffs nearby farm plots." },
            { "恢复需要发动拱地能力；金币不是每次必出。", "Use the rooting ability to recover; coins are not guaranteed on each use." },
            { "昼夜马", "Day-night horse" },
            { "北欧坐骑，随昼夜改变外观和速度，黎明与黄昏速度较高。", "A Norse mount whose appearance and speed change with time, becoming faster around dawn and dusk." },
            { "在草地进食恢复；外观可帮助判断森林中的时间。", "Feeds on grass; its appearance helps tell time in forests." },
            { "海马", "Sea-horse" },
            { "奥林匹斯坐骑，可发动短时高速冲刺。", "An Olympus mount with a brief high-speed dash." },
            { "可在任意地形以水恢复；冲刺有冷却。", "Recovers with water on any terrain; the dash has a cooldown." },
            { "地狱三头犬", "Cerberus" },
            { "奥林匹斯坐骑，可召唤幽灵军队协助战斗。", "An Olympus mount that summons a ghostly squad to fight." },
            { "在草地挖骨头恢复；幽灵部队是能力效果，不计为永久人口。", "Digs up bones on plains to recover; ghost troops are an ability effect, not permanent population." },
            { "阿拉克涅", "Arachne" },
            { "奥林匹斯蜘蛛坐骑，可放下蛛网减缓贪婪怪。", "An Olympus spider mount that drops webs to slow Greed." },
            { "在森林中捕食昆虫恢复；草地不能代替森林进食。", "Feeds on insects in forests; grass cannot replace forest feeding." },
            { "太阳战车", "Chariot of Helios" },
            { "奥林匹斯坐骑，白天可获得短时高速冲刺。", "An Olympus mount with a brief speed burst during the day." },
            { "在草地进食恢复；同一解锁点选择日或月战车会锁定另一选项。", "Feeds on grass; choosing the day or night chariot at the shrine locks the other choice." },
            { "月亮战车", "Chariot of Selene" },
            { "奥林匹斯坐骑，夜间可获得短时高速冲刺。", "An Olympus mount with a brief speed burst at night." },
            { "飞马", "Pegasus" },
            { "奥林匹斯坐骑，可发动长距离跳跃跨越敌群。", "An Olympus mount that makes long jumps over groups of enemies." },
            { "在草地进食恢复；跳跃消耗耐力，落点仍需安全。", "Feeds on grass; jumping uses stamina and still requires a safe landing." },
            { "驴", "Donkey" },
            { "奥林匹斯坐骑，可放下面包招募附近游民，并在进食后产出金币。", "An Olympus mount that drops bread to recruit nearby vagrants and produces coins after feeding." },
            { "在草地进食恢复；面包能力不是直接增加工具职业。", "Feeds on grass; bread does not directly create a tool profession." },
            { "阿尔戈斯", "Argos" },
            { "奥林匹斯猎犬坐骑，可给予附近臣民速度增益，帮助人员撤退。", "An Olympus hound that grants nearby subjects a speed bonus to help them retreat." },
            { "在森林中恢复饱食；留意增益的持续时间。", "Recovers its well-fed bonus in forests; watch the buff duration." },
            { "奇美拉", "Chimera" },
            { "奥林匹斯坐骑，可发动火焰冲锋攻击敌人。", "An Olympus mount that attacks enemies with a fiery charge." },
            { "在草地捕食恢复；留意连续冲锋次数与冷却。", "Feeds on plains; watch consecutive charge uses and cooldown." },
            { "彩虹小马", "Rainbow pony" },
            { "周年活动坐骑，可高速冲刺，并在进食后产出金币。", "An anniversary-event mount that dashes quickly and produces coins after feeding." },
            { "冲刺不会伤害敌人；产币有冷却。", "Its dash does not damage enemies; coin production has a cooldown." },
            { "基础容量", "Base capacity" },
            { "能否建设由实际区域与锁定条件决定；边界并不是城墙。", "Building availability follows region and lock conditions; a border is not a wall." },
            { "标记王国建设区域与防线边界。", "Marks the kingdom building region and defensive boundary." },
            { "王国边界", "Kingdom border" },
            { "查看实际缺少条件；外形像坐骑，但不是普通坐骑解锁点。", "Check the missing requirements; despite its shape, it is not a normal mount unlock." },
            { "奥林匹斯战役的任务建造设施，需补齐轮子和王冠等任务部件。", "An Olympus quest construction requiring parts such as wheels and a crown." },
            { "需要施工与人员；不能直接套用常规战役炸弹船队的用途。", "Requires construction and crew; do not apply the standard bomb expedition rules." },
            { "奥林匹斯主题建造用于航行与海上作战的船只。", "In Olympus, builds ships for travel and naval combat." },
            { "科技解锁后仍要支付各建筑升级费用并完成施工。", "Buildings still need separate payments and construction after technology unlock." },
            { "常规主题的石矿用于解锁中阶建设科技；北欧使用对应木材科技。", "The stone site unlocks intermediate construction technology; Norse uses a corresponding wood technology." },
            { "中阶建设科技设施", "Intermediate technology site" },
            { "这是支付解锁，不要求君主携带铁矿石；科技解锁仍不等于建筑已升级。", "Pay to unlock; carrying iron ore is not required, and buildings still need upgrades." },
            { "常规主题的铁矿用于解锁高阶建设科技；北欧以木材科技设施替代。", "The iron mine unlocks advanced building technology in standard campaigns; Norse uses a wood technology site." },
            { "高阶建设科技设施", "Advanced technology site" },
            { "存款与钱袋是不同位置的金币；不要把银行数字当作随身可支付金额。", "Savings and wallet coins are separate; stored coins are not immediately carried spending money." },
            { "接收金币存入国库，在可用时段可向君主返还存款。", "Stores deposited coins and returns savings during available hours." },
            { "银行／银行家", "Bank / banker" },
            { "需要农舍、空间和可用地块；买工具本身不会产生农田收入。", "Requires a farm, space and available plots; buying tools alone produces no crop income." },
            { "供待业平民领取并成为农民，耕种可用农田或参与季节性采集。", "Villagers take farming tools to cultivate available plots or gather seasonal resources." },
            { "投石车、弩炮与火焰塔使用工匠，不是独立的人口职业。", "Catapults, ballistae and fire towers use builders, not separate professions." },
            { "供待业平民领取并成为工匠，负责建造、维修和操作工程设施。", "Villagers take hammers to become builders for construction, repair and siege machines." },
            { "工具库存与已装备人员分别统计；已有弓手也可能转入塔楼或部队。", "Stock and equipped subjects are separate; archers may move to towers or squads." },
            { "供待业平民领取并成为弓箭手，参与狩猎、守城或部队。", "Villagers take bows to become archers for hunting, defense or squads." },
            { "这里的居民需向房屋支付招募费用，不会捡地上的招募金币或追逐面包。", "Residents require house payment; they do not pick up recruitment coins or follow bakery treats." },
            { "在原游民营地遗址建造，提供付费招募待业平民的入口。", "Built on a former vagrant camp site to recruit villagers by paying the house." },
            { "可提前用金币招募赶来的游民以节省消耗品；不吸引市民之家的居民。", "Recruit arrivals with coins before they eat to save treats; citizen house residents are not attracted." },
            { "制作食物或饮品吸引游民；游民吃下后自动成为待业平民。", "Treats attract vagrants; eating one recruits them as villagers." },
            { "剩余天数", "Days remaining" },
            { "待激活", "Not activated" },
            { "待解锁", "Not unlocked" },
            { "已激活", "Activated" },
            { "雕像状态：", "Statue status: " },
            { "该坐骑的专属能力尚未核实；实时耐力与冷却见状态面板。", "This mount's ability has not been verified; see the live stamina and cooldown panel." },
            { "该隐士种类的专属改造尚未核实。", "This hermit's specific conversion has not been verified." },
            { "；", "; " },
            { "解锁", "Unlock " },
            { "小屋", " cottage" },
            { "改造后需要操作工匠。", "The converted tower requires builders." },
            { "将满足条件的弓箭塔改造成火焰塔。", "Converts an eligible archer tower into a fire tower." },
            { "火焰隐士", "Fire hermit" },
            { "增加招募入口，不会直接增加人口或自动晋升。", "Adds a recruitment point, not population or automatic promotions." },
            { "将满足条件的弓箭塔改造成额外军队招募塔。", "Converts an eligible archer tower into an extra squad recruitment tower." },
            { "军队招募隐士", "Warrior hermit" },
            { "需要购买消耗品；留意游民是否真正完成招募。", "Buy consumables and check whether arrivals have been recruited." },
            { "将满足条件的弓箭塔改造成吸引游民的面包或酿造设施。", "Converts an eligible archer tower into a bakery or brewery to attract vagrants." },
            { "面包／酿造隐士", "Bakery / brewery hermit" },
            { "改造后由工匠操作，不再是普通弓手驻塔。", "Builders operate the converted tower instead of ordinary tower archers." },
            { "将满足条件的弓箭塔改造成弩炮塔。", "Converts an eligible archer tower into a ballista tower." },
            { "弩炮隐士", "Ballista hermit" },
            { "召集会集中兵力，注意另一侧防线。", "Rallying concentrates troops; watch the opposite side." },
            { "将满足条件的城墙改造成号角城墙，用于召集军队。", "Converts an eligible wall into a war horn rally wall." },
            { "号角隐士", "Horn hermit" },
            { "改造会替换农田用途，先考虑粮食收入。", "Conversion replaces farming; consider the income loss." },
            { "将满足条件的农舍改造成马厩，用于管理坐骑。", "Converts an eligible farmhouse into a stable for mount management." },
            { "马厩隐士", "Stable hermit" },
            { "当前交互不可用；原因未提供", "Interaction unavailable; reason not provided" },
            { "队长（未细分）", "Leaders (unclassified)" },
            { "侍从", "Squires" },
            { "奥林匹斯主题提高重装步兵的攻击频率。", "In Olympus, increases hoplite attack rate." },
            { "重装步兵雕像", "Hoplite statue" },
            { "剩余天数与当前状态由实际对象读取。", "Remaining days and status come from the current object." },
            { "付费延长骷髅岛的倒计时，推迟火山喷发。", "Payment extends the Skull Island countdown and delays the eruption." },
            { "沙漏雕像", "Hourglass statue" },
            { "注意另一侧防线，召集不会增加士兵数量。", "Watch the opposite defense; rallying does not add troops." },
            { "吹响号角召集军队到这一侧，集中防御。", "The horn rallies forces to this side for concentrated defense." },
            { "号角城墙", "War horn wall" },
            { "具体升级条件需结合当前对象；不能当作普通弓箭塔。", "Check the current object's requirements; not a standard archer tower." },
            { "北欧主题的特殊改造设施，与狂战士升级有关。", "A Norse conversion associated with berserker upgrades." },
            { "狂战士改造塔", "Berserker tower" },
            { "需要火焰隐士和操作工匠；不是弓手驻塔。", "Requires the fire hermit and builders; not an archer tower." },
            { "由工匠操作，发射火焰投射物支援防线。", "Builders operate it to launch fire projectiles at enemies." },
            { "火焰塔", "Fire tower" },
            { "招募后仍需弓手组成部队，晋升装备需另购。", "Squads still need archers; promotion equipment is purchased separately." },
            { "隐士改造后的额外军队招募点，可购买盾牌招募基础队长。", "An extra shield recruitment point created through hermit conversion." },
            { "军队招募塔", "Squad recruitment tower" },
            { "这与城堡招募侍从的军队旗不同；不会直接增加人口。", "Different from squad recruitment banners; does not add population." },
            { "北欧主题为已有人员提供盾牌，支持持盾防御与部队编组。", "Equips existing Norse subjects with shields for defense and squad membership." },
            { "盾牌商店", "Shield shop" },
            { "需要已有基础队长；库存表示装备件数，不是骑士人数。", "Requires a basic leader; stock counts equipment, not knights." },
            { "购买装备供已有侍从领取，晋升为骑士或主题对应的高级队长。", "Existing squires collect this equipment to become knights or equivalent advanced leaders." },
            { "骑士升级装备", "Knight upgrade equipment" },
            { "查看当前谜题和能力提示。", "Check the current puzzle and ability prompt." },
            { "北欧战役的能力或谜题对象，具体阶段作用尚未核实。", "A Norse power or puzzle object whose stage-specific effect is not verified." },
            { "阿耳忒弥斯相关设施", "Artemis-related structure" },
            { "查看当前任务、货物和缺少条件。", "Check the current quest, cargo and missing requirements." },
            { "奥林匹斯战役的神祇任务对象，具体阶段作用尚未核实。", "An Olympus deity quest object whose stage-specific effect is not verified." },
            { "赫淮斯托斯相关设施", "Hephaestus-related structure" },
            { "按当前任务提示处理，不能套用普通悬崖洞穴流程。", "Follow the quest prompt rather than the standard cliff cave procedure." },
            { "奥林匹斯战役的特殊对象，具体阶段作用尚未核实。", "An Olympus campaign object whose stage-specific effect is not verified." },
            { "涉及君主或主题解锁的特殊交互，当前尚未核实专属作用。", "A special ruler or campaign interaction; the specific effect has not been verified." },
            { "优先查看已识别的原生种类和当前任务提示。", "Check the native identity and current quest prompt." },
            { "该名称的具体对象用途尚未核实；不应仅凭名称判断为任务或隐士。", "The specific object is not verified; its name alone does not identify a quest or hermit." },
            { "珀耳塞福涅相关设施", "Persephone-related structure" },
            { "未细分雕像", "Unclassified statue" },
            { "不要仅凭外观判断科技或能力；查看当前任务提示。", "Do not infer a technology or ability from appearance; check the quest prompt." },
            { "特殊设施的效果由战役及具体对象决定，当前尚未核实专属作用。", "Its effect depends on the campaign and object; the specific effect has not been verified." },
            { "仅招募不会自动成为工匠、弓手或农民。", "Recruitment alone does not make a builder, archer or farmer." },
            { "获得招募金币后成为待业平民，再领取工具进入对应职业。", "A recruitment coin turns a vagrant into a villager, who then takes equipment for a profession." },
            { "需要投石车及操作工匠；桶的数量不是士兵人数。", "Requires a catapult and builders; barrel stock is not troop count." },
            { "供投石车使用的火焰弹药，用于点燃敌群。", "Ammunition for catapults that sets enemy groups on fire." },
            { "由马厩隐士改造农舍；原农田生产功能会被替换。", "The stable hermit converts a farmhouse, replacing its farming function." },
            { "管理已解锁的坐骑，可在马厩更换可用坐骑。", "Houses unlocked mounts and allows switching to available steeds." },
            { "扑翼消耗耐力；查看当前能力与疲劳状态。", "Wing attacks consume stamina; check ability and fatigue status." },
            { "可用扑翼击退敌人；以进食恢复耐力，不依赖草地。", "Can knock enemies back with a wing attack and feeds without needing grass." },
            { "需要农民；被敌人阻断或人员不足时不会立即获得收入。", "Requires farmers; blocked routes or missing workers delay income." },
            { "冬季可付费指派农民采集，提供季节性金币收入。", "Can be paid in winter to send farmers gathering for coin income." },
            { "收入需要等待返回；特殊战役的交付规则可能不同。", "Payment is followed by a return trip; special campaigns may use other rules." },
            { "常规主题付费派遣商人，翌日返回后交付金币。", "In standard campaigns, a paid merchant returns the next day with coins." },
            { "解锁隐士不等于完成建筑改造，还需合适建筑和后续费用。", "Unlocking is separate from conversion, which needs an eligible building and payment." },
            { "解锁对应种类的隐士；隐士可帮助改造特定建筑。", "Unlocks a hermit who enables a specific building conversion." },
            { "解锁后可搭乘君主坐骑；具体种类优先按原生身份识别。", "After unlocking, can ride with a monarch; native identity determines the conversion." },
            { "帮助将满足条件的建筑改造成特殊设施，种类决定改造用途。", "Converts eligible buildings into special structures according to the hermit's type." },
            { "需要准备炸弹、工匠和护送部队；此流程不适用于奥林匹斯任务战役。", "Requires a bomb, builders and escort troops; Olympus uses a different quest campaign." },
            { "常规战役的敌方主巢；炸弹队伍可进入并引爆清除。", "The main greed nest in standard campaigns; an escorted bomb can destroy it from inside." },
            { "悬崖洞穴", "Cliff cave" },
            { "小传送门、码头传送门与悬崖洞穴的处理方式不同。", "Small portals, dock portals and cliff caves require different approaches." },
            { "敌人的出入口；攻破后可能引发反击。", "An enemy entry point; destroying it can trigger retaliation." },
            { "先确认出口位置；这与 Mod 的地图传送功能不同。", "Check the exit location; this is separate from the mod's map teleport." },
            { "由已清除的小传送门遗址建造，供君主在本岛快速移动。", "Built on a destroyed small portal site for travel within the island." },
            { "传送门", "Teleporter" },
            { "灯塔属于当前岛屿；升级前检查对应建设科技。", "Applies to this island; higher tiers require the appropriate technology." },
            { "保护返航船只，减少在已建灯塔的码头再次触礁损坏。", "Protects returning ships from wrecking at this island's dock." },
            { "吸引到达不等于已完成招募；及时查看游民与消耗品状态。", "Attraction is not recruitment; check arrivals and consumable stock." },
            { "制作吸引游民靠近的食物或饮品，帮助补充人口。", "Produces food or drinks that attract vagrants to replenish population." },
            { "面包／酿造设施", "Bakery / brewery" },
            { "需要弩炮隐士完成改造；不会招募新职业。", "Requires the ballista hermit for conversion; does not recruit a new profession." },
            { "由工匠操作的大型弩炮，用弩箭支援防线。", "A builder-operated defensive tower that fires large bolts." },
            { "弩炮塔", "Ballista tower" },
            { "守住操作位置；火焰桶是另行购买的弹药。", "Protect its position; fire barrels are purchased separately." },
            { "由工匠操作，向敌群抛射石弹支援防线。", "Builders operate it to throw stones at enemy groups." },
            { "先准备工匠与安全路线；投石车不是一种新的职业。", "Requires builders and a safe route; catapults are not a separate profession." },
            { "购买投石车，由工匠建造、推至对应一侧防线并操作。", "Orders catapults that builders assemble, move to the selected side and operate." },
            { "投石车工坊", "Catapult workshop" },
            { "忍者会在城外森林伏击；森林位置影响可用伏击点。", "Ninjas ambush enemies in forests outside the walls; forest locations matter." },
            { "幕府主题出售忍者武器，供待业平民领取并成为忍者。", "Supplies ninja weapons that turn villagers into ninjas in Shogun." },
            { "武器会损耗；工具库存不等于已装备士兵人数。", "Weapons wear out; equipment stock is not the number of equipped soldiers." },
            { "供待业平民领取并成为长枪兵，参与守城与捕鱼；主题变体可能不同。", "Turns villagers into pikemen for defense and fishing; campaign variants may differ." },
            { "需要已有基础队长；支付购买装备不会直接增加人口。", "Requires a basic squad leader; buying equipment does not add population." },
            { "常规主题出售升级装备，由已有侍从领取后晋升为骑士或主题对应的高级队长。", "In standard campaigns, supplies equipment that promotes existing squires to knights or equivalent advanced leaders." },
            { "队长会带领弓手；后续领取锻造装备可晋升。出征状态与招募状态不同。", "Leaders recruit archers and can be promoted with forge equipment; attack and recruitment are different actions." },
            { "购买盾牌供待业平民领取，成为侍从等主题对应的基础队长。", "Provides a shield for a villager to become a squire or the campaign's basic squad leader." },
            { "军队招募旗", "Squad recruitment banner" },
            { "农田需要空间和农民；改为马厩后不能继续当农舍使用。", "Requires space and farmers; conversion to a stable replaces the farm function." },
            { "支持周边农田；升级为水车农舍后，农民可在附近留宿。", "Supports nearby fields; the millhouse upgrade allows farmers to stay nearby overnight." },
            { "先解锁建设科技，再支付升级；升级仍需要工匠施工。", "Unlock the required technology first; paid upgrades still need builders." },
            { "提升王国建设阶段，开放对应的工具、军队与设施。", "Advances the kingdom to unlock equipment, troops and facilities." },
            { "驻塔弓手会离开地面狩猎与部队岗位，建设前考虑位置。", "Tower archers leave ground hunting and squad duties; choose the site carefully." },
            { "供弓箭手驻守射击；容量、遮蔽和特殊改造随等级变化。", "Provides archer firing positions; capacity, cover and conversions depend on the tier." },
            { "弓箭塔", "Archer tower" },
            { "升级需要工匠施工，夜间施工会削弱防守。", "Upgrades require builders and can weaken defenses during construction." },
            { "阻挡地面敌人，保护城内人员；飞行敌人可越过城墙。", "Blocks ground enemies; flying enemies can pass over walls." },
            { "弓箭手雕像", "Archer statue" },
            { "工匠雕像", "Builder statue" },
            { "农民雕像", "Farmer statue" },
            { "骑士雕像", "Knight statue" },
            { "提高弓箭手的射击精准度，帮助狩猎与防守。", "Improves archer accuracy for hunting and defense." },
            { "强化城墙的耐久，提升防线承受攻击的能力。", "Reinforces walls to withstand more attacks." },
            { "增加农场可支持的农田地块；仍需足够空间和农民。", "Increases supported farm plots; requires space and farmers." },
            { "赋予骑士突进攻击能力；不作用于未升级的侍从。", "Grants knights a lunge attack; does not affect squires." },
            { "先解锁，再支付激活费用；当前费用与状态以实际对象为准。", "Unlock first, then pay to activate; cost and status come from the current object." },
            { "该雕像的专属作用尚未核实；请查看游戏提示。", "This statue's effect has not been verified; check the game prompt." },
            { "当前费用与状态以实际对象为准。", "Cost and status come from the current object." },
                        { "王国顾问", "Kingdom Advisor" },
            { "炸弹", "Bomb" },
            { "由工匠推动并由部队护送，用于炸毁悬崖洞穴。", "Pushed by builders and escorted by troops to destroy the cliff cave." },
            { "准备护送人员和金币；进入洞穴后的引爆与撤离以游戏交互提示为准。", "Prepare an escort and coins; follow the game's prompts for detonation and escape inside the cave." },
            { "炸弹出征旗", "Bomb expedition banner" },
            { "购买炸弹并组织部队护送，用于进攻悬崖洞穴。", "Purchase a bomb and assemble its escort to attack the cliff cave." },
            { "出征前准备工匠、军队和金币，确认护送路线安全。", "Prepare builders, troops and coins, and ensure the escort route is safe." },
            { "军队", "Army" },
            { "当前无升级交互", "No upgrade interaction available" },
            { "附近建筑详情", "Nearby building details" },
            { "狂战士", "Berserkers" }, { "待业平民", "Unassigned citizens" }, { "忍者", "Ninjas" }, { "渔夫", "Fishers" }, { "马厩管理员", "Stable keepers" },
            { "图鉴", "Catalog" },
            { "兴趣点", "Locations" },
            { "设置", "Settings" },
            { "地图", "Map" },
            { "岛屿记录", "Island journal" },
            { "资源", "Resources" },
            { "关闭", "Off" },
            { "开启", "On" },
            { "打开", "Open" },
            { "关闭面板", "Close panel" },
            { "顾问与提醒", "Advisor and alerts" },
            { "图鉴与进度", "Catalog and journal" },
            { "资源辅助", "Resource assistance" },
            { "移动与时间", "Movement and time" },
            { "手柄", "Controller" },
            { "键鼠", "Keyboard / mouse" },
            { "全部", "All" },
            { "防御", "Defense" },
            { "建设", "Construction" },
            { "经济", "Economy" },
            { "人口", "Population" },
            { "工具", "Tools" },
            { "航行", "Sailing" },
            { "科技", "Technology" },
            { "探索", "Exploration" },
            { "特殊", "Special" },
            { "环境", "Environment" },
            { "威胁", "Threat" },
            { "未分类", "Unclassified" },
            { "小地图", "Minimap" },
            { "地图背景", "Map background" },
            { "默认位置", "Default position" },
            { "顶部", "Top" },
            { "底部", "Bottom" },
            { "透明", "Transparent" },
            { "面板", "Panel" },
            { "情报范围", "Intel scope" },
            { "本次探索", "Explored this visit" },
            { "全岛", "Whole island" },
            { "树木", "Tree" },
            { "建筑", "Buildings" },
            { "营地与人口", "Camps and population" },
            { "敌人", "Enemies" },
            { "特殊地点", "Special locations" },
            { "王国顾问卡片", "Kingdom advisor" },
            { "Player 详情卡片", "Nearby details" },
            { "顾问背景", "Advisor background" },
            { "附近详情背景", "Nearby details background" },
            { "提醒背景", "Alert background" },
            { "主界面背景", "Main panel background" },
            { "人口与科技", "Population and technology" },
            { "用途与升级建议", "Uses and upgrade tips" },
            { "情境提醒", "Situational alerts" },
            { "防线风险提醒", "Defense alerts" },
            { "建设与招募缺口", "Staffing alerts" },
            { "坐骑能力状态", "Mount status" },
            { "图鉴图标", "Catalog icons" },
            { "岛屿进度记录", "Island journal" },
            { "字号", "Font size" },
            { "恢复卡片默认位置", "Reset HUD positions" },
            { "执行", "Apply" },
            { "无限钱袋容量", "Unlimited purse capacity" },
            { "手动添加资源", "Add resources manually" },
            { "地图长按传送", "Hold to teleport on map" },
            { "无限耐力", "Unlimited stamina" },
            { "游戏速度", "Game speed" },
            { "暂停", "Paused" },
            { "正常", "Normal" },
            { "2 倍", "2x" },
            { "4 倍", "4x" },
            { "常驻手柄光标", "Always show controller cursor" },
            { "光标速度", "Cursor speed" },
            { "慢", "Slow" },
            { "标准", "Standard" },
            { "快", "Fast" },
            { "很快", "Very fast" },
            { "呼出按键", "Panel button" },
            { "左摇杆按压 L3", "Left stick click (L3)" },
            { "右摇杆按压 R3", "Right stick click (R3)" },
            { "按下左摇杆", "Click left stick" },
            { "按下右摇杆", "Click right stick" },
            { "按下左摇杆短按面板", "Click left stick for panel" },
            { "删除", "Delete" },
            { "清空", "Clear" },
            { "完成", "Done" },
            { "自动", "Auto" },
            { "简体中文", "Simplified Chinese" },
            { "语言", "Language" },
            { "语言 / Language", "Language" },
            { "金币", "Coins" },
            { "宝石", "Gems" },
            { "骷髅", "Skulls" },
            { "灵魂", "Shades" },
            { "幽魂", "Shades" },
            { "工匠", "Builders" },
            { "弓手", "Archers" },
            { "弓箭手", "Archers" },
            { "骑士", "Knights" },
            { "农民", "Farmers" },
            { "游民", "Vagrant" },
            { "长枪兵", "Pikemen" },
            { "钱袋", "Purse" },
            { "坐骑", "Mount" },
            { "耐力", "Stamina" },
            { "饱食", "Fed" },
            { "疲劳", "Tired" },
            { "基础", "Basic" },
            { "中阶已解锁", "Stone technology unlocked" },
            { "高阶已解锁", "Iron technology unlocked" },
            { "中阶", "Stone" },
            { "高阶", "Iron" },
            { "建设科技", "Construction technology" },
            { "联机", "Online" },
            { "资源合计", "Total resources" },
            { "原生钱袋", "Native purse" },
            { "无限容量 · 数字钱袋", "Unlimited capacity · Numeric purse" },
            { "岛屿地图 ⇄", "Island map ⇄" },
            { "地图加载中…", "Loading map…" },
            { "可招募", "Recruitable" },
            { "营地", "Camps" },
            { "敌情未知", "Enemy data unavailable" },
            { "全岛 →", "Island →" },
            { "附近 →", "Nearby →" },
            { "附近交互", "Nearby interaction" },
            { "开启小地图", "Show minimap" },
            { "春季", "Spring" },
            { "夏季", "Summer" },
            { "秋季", "Autumn" },
            { "冬季", "Winter" },
            { "白昼", "Daytime" },
            { "夜晚", "Night" },
            { "上一页", "Prev" },
            { "下一页", "Next" },
            { "详情", "Details" },
            { "列表", "List" },
            { "上一地点", "Previous location" },
            { "下一地点", "Next location" },
            { "类别", "Category" },
            { "筛选", "Filter" },
            { "数量", "Amount" },
            { "快捷数量", "Preset amount" },
            { "玩家", "Player" },
            { "当前资源", "Selected resource" },
            { "仅金币", "Coins only" },
            { "全部钱袋资源", "All purse resources" },
            { "清空范围", "Clear scope" },
            { "清空所选资源", "Clear selected resources" },
            { "添加", "Add" },
            { "当前", "Current" },
            { "最近记录第", "Last recorded on day" },
            { "点击搜索 · 中文 / 英文", "Search · Chinese / English" },
            { "没有匹配条目。清空搜索或切换类别。", "No matching entries. Clear the search or change category." },
            { "当前筛选没有兴趣点。", "No points match this filter." },
            { "当前筛选没有地点。切换兴趣点分类或地图情报范围。", "No locations match this filter. Change category or map scope." },
            { "靠近建筑、工具或坐骑，查看用途与升级条件。", "Approach a building, tool or mount to see its purpose and upgrade requirements." },
            { "岛屿进度记录已关闭，可在设置中开启。", "Island journal is disabled. Enable it in Settings." },
            { "进入岛屿后自动记录已读取的情报。", "Observed information is recorded automatically after entering an island." },
            { "这是最近观察记录，离岛后不会实时更新。", "This is the last observation. It is not updated while you are away." },
            { "即时保存 · 玩法辅助默认关闭 · 单机与联机均开放", "Saved immediately · Gameplay assists off by default · Available offline and online" },
            { "上下选择，左右调整；数量可直接输入，范围 1–10000。只显示当前主题支持的资源。无限钱袋只扩充容量，需在资源辅助设置中开启。", "Navigate up/down, adjust left/right. Enter an amount from 1 to 10000. Only resources supported by this campaign are shown. Unlimited capacity is a separate option under Resource assistance." },
            { "手柄搜索 · 输入英文关键词；中文条目也可按类别浏览。", "Controller search · Enter English keywords, or browse by category." },
            { "上下选择 · 左右分类 · Enter 选择 · Tab 切页 · Esc 关闭", "Up/down: select · Left/right: category · Enter: confirm · Tab: tabs · Esc: close" },
            { "短按面板／长按显隐 · LB/RB 页签 · LT/RT", "Tap: panel / Hold: HUD · LB/RB: tabs · LT/RT:" },
            { "翻页 · 方向选择 · 确认／返回", "pages · D-pad: select · A/B: confirm/back" },
            { "右摇杆 · 光标 / 呼出键长按 · 显隐", "Right stick: cursor / Hold panel button: HUD" },
            { "页签", "tabs" },
            { "翻页", "pages" },
            { "方向选择", "D-pad: select" },
            { "确认／返回", "A/B: confirm/back" },
            { "短按面板／长按显隐", "Tap: panel / Hold: HUD" },
            { "升级条件", "Upgrade requirements" },
            { "升级目标", "Next upgrade" },
            { "本岛同类交互点", "Matching locations on this island" },
            { "费用、等级和锁定原因请靠近对象查看。不同主题以当前游戏数据为准。", "Approach an object for its cost, level and lock reason. Campaign-specific details come from the current game." },
            { "建议", "Tip" },
            { "费用", "Cost" },
            { "等级", "Level" },
            { "库存", "Stock" },
            { "耐久", "Health" },
            { "初始", "Initial" },
            { "驻防", "Garrison" },
            { "施工", "Building" },
            { "锁定", "Locked" },
            { "招募", "Recruit" },
            { "可交互", "Available" },
            { "暂不可用", "Unavailable" },
            { "已满", "Full" },
            { "已达容量", "At capacity" },
            { "处名称密集 · 切换附近查看", "labels overlap · Switch to Nearby" },
            { "秒 · 松开取消", "s · Release to cancel" },
            { "传送", "Teleport" },
            { "钱袋为空 · 留意收入与返程安全", "Purse empty · Watch your income and return route" },
            { "缺少工匠 · 建设和维修可能停滞", "No builders · Construction and repairs may stop" },
            { "夜间施工 · 先确认防线安全", "Night construction · Check your defenses first" },
            { "防线城墙已失守", "outer wall has fallen" },
            { "最外城墙耐久不足一半", "outer wall is below half health" },
            { "敌群接近最外城墙", "enemies are approaching the outer wall" },
            { "左侧", "Left" },
            { "右侧", "Right" },
            { "处工具库存为空", "tool stocks are empty" },
            { "处 · 缺少工匠", "sites · No builders" },
            { "单次数量为 1–10000", "Amount must be between 1 and 10000" },
            { "数量必须是 1–10000", "Amount must be between 1 and 10000" },
            { "本局未发现此资源类型", "This resource is not available in the current session" },
            { "地图传送尚未开启", "Map teleport is disabled" },
            { "请先进入存档", "Load a save first" },
            { "目标玩家不在本机控制范围", "This player is not controlled locally" },
            { "地点已变化，请重新选择", "The location changed. Select it again" },
            { "地面尚未加载", "Ground has not loaded yet" },
            { "此处不在已加载地面范围内", "This location is outside the loaded ground" },
            { "此地点靠近岛屿边界，无法验证安全落点", "Cannot verify a safe landing near the island boundary" },
            { "玩家移动组件不可用", "Player movement component is unavailable" },
            { "世界时间控制器尚未加载", "World time controller has not loaded yet" },
            { "已清空所选钱袋资源", "Selected purse resources cleared" },
            { "清空失败", "Clear failed" },
            { "已传送", "Teleported" },
            { "传送失败", "Teleport failed" },
            { "添加失败", "Add failed" },
            { "游戏实际处理结果", "Actual game result" },
            { "操作辅助出错，已关闭", "Assistance failed and was disabled" },
            { "手柄输入读取失败，请查看日志", "Controller input failed. Check the log" },
            { "人", " people" },
            { "只", " enemies" },
            { "处", " locations" },
            { "秒", "s" },
            { "天", " days" },
            { "岛", "Island" },
            { "第", "Day" },
            { "收起", "Hide" },
            { "城墙", "Wall" },
            { "塔楼", "Tower" },
            { "城堡／营地中心", "Castle / town center" },
            { "城堡", "Castle" },
            { "营地中心", "Camp center" },
            { "农舍", "Farmhouse" },
            { "农田", "Farm" },
            { "游民营地", "Vagrant camp" },
            { "难民营", "Vagrant camp" },
            { "市民之家", "Citizen house" },
            { "弓箭工具", "Bow equipment" },
            { "工匠工具", "Builder equipment" },
            { "农民工具", "Farmer equipment" },
            { "长枪工具", "Pike equipment" },
            { "盾牌／军队设施", "Shield / Army station" },
            { "忍者设施", "Ninja dojo" },
            { "锻造设施", "Forge" },
            { "工坊", "Workshop" },
            { "投石车", "Catapult" },
            { "弩炮设施", "Ballista" },
            { "面包设施", "Bakery" },
            { "灯塔", "Lighthouse" },
            { "码头", "Dock" },
            { "船只", "Boat" },
            { "船坞", "Boatyard" },
            { "传送设施", "Teleporter" },
            { "敌方传送门", "Greed portal" },
            { "洞穴／山体据点", "Cave / Cliff stronghold" },
            { "科技设施", "Technology site" },
            { "雕像", "Statue" },
            { "纪念碑／特殊设施", "Monument / special structure" },
            { "隐士小屋", "Hermit cottage" },
            { "隐士", "Hermit" },
            { "宝箱", "Chest" },
            { "银行设施", "Bank" },
            { "商人", "Merchant" },
            { "浆果丛", "Berry bush" },
            { "马匹", "Horse" },
            { "狮鹫", "Griffin" },
            { "马厩", "Stable" },
            { "木马设施", "Trojan horse" },
            { "巨蛇相关设施", "Serpent-related structure" },
            { "赫淮斯托斯设施", "Hephaestus site" },
            { "珀耳塞福涅设施", "Persephone site" },
            { "阿耳忒弥斯设施", "Artemis site" },
            { "雷神相关设施", "Thor-related structure" },
            { "海拉相关设施", "Hel-related structure" },
            { "宝石保管员", "Gem keeper" },
            { "宝石储存", "Gem storage" },
            { "边界设施", "Border site" },
            { "蛋", "Egg" },
            { "火焰桶", "Fire barrel" },
            { "货物", "Cargo" },
            { "君主墓地", "Monarch grave" },
            { "蜡烛", "Candle" },
            { "王冠", "Crown" },
            { "召集铃", "Call bell" },
            { "飞行怪", "Floater" },
            { "贪婪怪", "Greedling" },
            { "巨型怪", "Breeder" },
            { "木制", "Wood" },
            { "石制", "Stone" },
            { "铁制", "Iron" },
            { "未建造", "Not built" },
            { "阻挡敌人，保护城内人员。", "Blocks enemies and protects people inside the walls." },
            { "升级会进入施工阶段；危险时段先确认防线仍能承受攻击。", "Upgrading starts construction. During dangerous hours, make sure your defenses can still withstand attacks." },
            { "提供驻守位置，协助防守附近区域。", "Provides garrison positions to defend the surrounding area." },
            { "不同等级与特殊改造用途不同；升级目标以当前对象为准。", "Levels and special upgrades serve different purposes. Check the actual object for its next upgrade." },
            { "提升王国建设阶段，解锁对应设施。", "Advances the kingdom's construction tier and unlocks facilities." },
            { "科技解锁与城堡等级是不同前置条件。", "Technology and castle level are separate requirements." },
            { "王国的中心，也是早期建设入口。", "The kingdom's center and its first construction site." },
            { "先稳定招募、工具和两侧防线，再向外扩张。", "Secure recruitment, tools and both defenses before expanding." },
            { "支持周边农田生产，升级后用途随主题和等级变化。", "Supports nearby farming. Upgraded behavior depends on the campaign and level." },
            { "需要农民和可用农田；冬季应留意收入来源。", "Requires farmers and usable farmland. Watch your sources of income in winter." },
            { "供农民耕作并产生收入。", "Allows farmers to grow crops and generate income." },
            { "建设后还需要人员；数量不等于正在生产的数量。", "Staff are needed after construction. The total count is not the number of productive sites." },
            { "招募新成员的来源。", "A source of new recruits." },
            { "扩张或清理附近森林前，留意营地是否会受到影响。", "Check whether expansion or nearby forest clearing will affect the camp." },
            { "可招募成为王国成员。", "Can be recruited into the kingdom." },
            { "招募后需要合适的工具才能从事对应职业。", "Recruits need the appropriate tools to take on a job." },
            { "提供招募人口的入口。", "Provides a place to recruit people." },
            { "费用及招募状态以实际对象为准。", "Check the actual object for its cost and recruitment status." },
            { "用于配置弓箭手，支持狩猎和防御。", "Equips archers for hunting and defense." },
            { "工具库存与已配置人员是两项不同统计。", "Tool stock and equipped workers are separate counts." },
            { "用于配置工匠，承担建造和维修。", "Equips builders for construction and repairs." },
            { "扩张前保证工匠能安全抵达施工位置。", "Make sure builders can reach construction sites safely before expanding." },
            { "用于配置农民，支持农田生产。", "Equips farmers to work the fields." },
            { "应同时检查可用农田与农民人数。", "Check both usable farmland and the number of farmers." },
            { "用于配置对应近战守卫。", "Equips the corresponding melee guards." },
            { "用途与可用性随主题变化。", "Purpose and availability vary by campaign." },
            { "用于军队相关配置或招募。", "Used to equip or recruit army units." },
            { "确认左右防线和军队配置后再投入资源。", "Check both defenses and army equipment before spending resources." },
            { "幕府主题的特殊人员设施。", "A special personnel facility in the Shogun campaign." },
            { "观察人员行为与当前防线需求。", "Watch the units' behavior and your current defense needs." },
            { "提供当前主题的装备或军队相关升级。", "Provides equipment or army upgrades for the current campaign." },
            { "具体购买结果以运行时升级目标为准。", "Check the actual upgrade target to see what a purchase provides." },
            { "生产防御或攻城相关设施。", "Produces defensive or siege equipment." },
            { "留意人员需求与设施移动到防线的时间。", "Allow for staffing requirements and travel time to the defenses." },
            { "支援防线的重型设施。", "Heavy equipment that supports the defenses." },
            { "建设与使用需要相应人员；保持移动路线安全。", "Building and operating it requires staff. Keep the travel route safe." },
            { "提供特殊防御能力。", "Provides specialized defensive capabilities." },
            { "特殊改造可能需要对应隐士。", "Special upgrades may require the corresponding hermit." },
            { "与吸引游民和人口补充有关。", "Helps attract vagrants and replenish the population." },
            { "关注消耗与实际招募结果。", "Monitor consumption and actual recruitment results." },
            { "改善岛屿航行相关设施。", "Improves facilities used for sailing between islands." },
            { "不同等级需要对应科技；先看升级前置条件。", "Different levels require appropriate technology. Check the requirements first." },
            { "船只与航行的交互位置。", "An interaction point for boats and sailing." },
            { "出航前检查人员、资源和当前岛屿防线。", "Check your crew, resources and island defenses before sailing." },
            { "用于岛屿间航行或当前主题的船队活动。", "Used for inter-island sailing or campaign-specific fleet activities." },
            { "施工、登船与出航是不同阶段。", "Construction, boarding and departure are separate stages." },
            { "与船只建造和船队有关。", "Related to boat construction and fleets." },
            { "费用和任务条件随战役变化。", "Costs and quest requirements vary by campaign." },
            { "用于快速移动或建立传送连接。", "Enables fast travel or a teleport connection." },
            { "先确认目的地安全与当前费用。", "Check the destination's safety and current cost first." },
            { "敌人相关的重要据点。", "An important enemy stronghold." },
            { "进攻前检查兵力、资源及反击风险。", "Check your forces, resources and counterattack risk before attacking." },
            { "战役推进相关的重要位置。", "An important location for campaign progress." },
            { "先确认当前战役的攻城条件。", "Check the current campaign's siege requirements first." },
            { "解锁更高阶段的建设科技。", "Unlocks a higher tier of construction technology." },
            { "金币支付与科技解锁不同于携带矿石材料。", "Paying coins and unlocking technology are separate from carrying ore materials." },
            { "解锁对应建设阶段。", "Unlocks the corresponding construction tier." },
            { "主题不同，设施名称与外观可能不同。", "The name and appearance can differ between campaigns." },
            { "提供增益、任务或特殊交互。", "Provides bonuses, quests or special interactions." },
            { "确认支付货币、持续状态和当前主题。", "Check the payment currency, active status and campaign." },
            { "与特殊能力、科技或任务有关。", "Related to special abilities, technology or quests." },
            { "先看实际锁定条件和支付结果。", "Check the actual lock requirements and payment result first." },
            { "与建筑特殊改造相关。", "Related to special building upgrades." },
            { "改造时可能需要带上对应隐士。", "An upgrade may require bringing the corresponding hermit." },
            { "特殊角色的解锁或招募入口。", "A place to unlock or recruit a special character." },
            { "解锁费用与后续改造费用需要分别考虑。", "Unlocking costs and later upgrade costs are separate." },
            { "提供资源或任务物品。", "Provides resources or quest items." },
            { "货币种类以当前对象为准。", "Check the actual object for the currency it uses." },
            { "与金币储存和经济管理有关。", "Related to coin storage and economic management." },
            { "钱袋金币与银行储存应分别理解。", "Coins in the purse and coins in the bank are separate." },
            { "提供主题相关的经济交互。", "Provides campaign-specific economic interactions." },
            { "观察当前费用与交付状态。", "Check the current cost and delivery status." },
            { "季节性经济资源。", "A seasonal source of income." },
            { "留意人员需求与当前季节。", "Watch staffing requirements and the current season." },
            { "可以付费砍伐，影响森林和可建设区域。", "Can be cut down for a fee, affecting the forest and buildable land." },
            { "砍树前检查附近游民营地与经济资源。", "Check nearby vagrant camps and income sources before cutting trees." },
            { "提供移动能力及主题相关特殊能力。", "Provides mobility and campaign-specific special abilities." },
            { "观察耐力、饱食和疲劳状态。", "Monitor stamina, feeding and exhaustion." },
            { "提供移动能力。", "Provides mobility." },
            { "奔跑消耗耐力；停留、步行和进食状态影响恢复。", "Running consumes stamina. Resting, walking and feeding affect recovery." },
            { "具有特殊能力的坐骑。", "A mount with special abilities." },
            { "能力可用性以当前玩家状态为准。", "Ability availability depends on the current player state." },
            { "与坐骑管理有关。", "Related to mount management." },
            { "具体容量与可用条件以当前对象为准。", "Check the actual object for its capacity and requirements." },
            { "奥林匹斯战役相关任务设施。", "A quest facility in the Call of Olympus campaign." },
            { "按实际缺少条件准备轮子、王冠等任务要素。", "Collect the missing quest items, such as wheels and crowns." },
            { "对应战役的特殊目标。", "A special objective in the corresponding campaign." },
            { "以当前任务和锁定提示为准。", "Follow the current quest and lock information." },
            { "奥林匹斯主题的特殊设施。", "A special facility in Call of Olympus." },
            { "查看当前任务条件和费用。", "Check the current quest requirements and cost." },
            { "查看任务条件与角色要求。", "Check the quest and character requirements." },
            { "北欧主题的特殊设施。", "A special facility in the Norse Lands campaign." },
            { "按当前任务提示操作。", "Follow the current quest instructions." },
            { "该对象尚未收录专属说明；费用和条件来自当前游戏。", "This object has no dedicated entry yet. Its costs and requirements come from the current game." },
            { "请以运行时提示为准。", "Follow the current game information." },
            { "与君主、能力或主题解锁有关。", "Related to rulers, abilities or campaign unlocks." },
            { "与宝石存取有关的交互入口。", "An interaction point for depositing or withdrawing gems." },
            { "管理当前战役中的宝石储存。", "Manages gem storage in the current campaign." },
            { "用于对应防御设施的消耗品。", "A consumable for the corresponding defensive facility." },
            { "钱袋持有和存放数量应分别理解。", "Resources carried in the purse and resources stored elsewhere are separate." },
            { "查看实际费用，出航前确认随行人员。", "Check the actual cost and confirm your crew before departure." },
            { "具体结果取决于当前战役。", "The result depends on the current campaign." },
            { "召集当前主题的相关人员或队伍。", "Calls the relevant personnel or teams for this campaign." },
            { "先确认防线与施工区域。", "Check your defenses and construction area first." },
            { "与王国扩张或对应主题的边界能力有关。", "Related to kingdom expansion or campaign-specific border abilities." },
            { "购买后还需要人员与相应设施。", "Staff and the appropriate facilities are still needed after purchase." },
            { "确认当前交互需要的货币。", "Check which currency this interaction requires." },
            { "条件已满足", "Requirements met" },
            { "当前没有可用升级", "No upgrade is currently available" },
            { "需要解锁对应的中阶建设科技", "Requires the corresponding stone construction technology" },
            { "需要解锁对应的高阶建设科技", "Requires the corresponding iron construction technology" },
            { "需要解锁或带上对应隐士", "Unlock or bring the corresponding hermit" },
            { "需要带上弩炮隐士", "Bring the ballista hermit" },
            { "需要带上面包师隐士", "Bring the baker hermit" },
            { "需要带上骑士隐士", "Bring the knight hermit" },
            { "需要带上马厩隐士", "Bring the stable hermit" },
            { "需要带上号角隐士", "Bring the horn hermit" },
            { "缺少所需金块", "Missing the required gold nuggets" },
            { "缺少木马轮子", "Missing Trojan horse wheels" },
            { "缺少木马所需王冠", "Missing crowns for the Trojan horse" },
            { "需要对应的火焰乘员", "Requires the corresponding fire crew member" },
            { "需要对应的珀耳塞福涅乘员", "Requires the corresponding Persephone crew member" },
            { "需要可用的船队船只", "Requires an available fleet boat" },
            { "已携带货物，需先处理现有货物", "Already carrying cargo. Handle it first" },
            { "巨蛇在门口，当前交互受阻", "The serpent blocks this interaction" },
            { "当前时机不允许；等待可用时段或冷却结束", "Unavailable now. Wait for the allowed time or cooldown" },
            { "当前区域不允许建设；检查王国边界和森林", "Cannot build here. Check kingdom borders and the forest" },
            { "对象暂时不可用；检查当前任务及施工状态", "Temporarily unavailable. Check the quest and construction status" },
            { "尚未解释的条件", "Unidentified requirement" },
            { "已解锁", "Unlocked" },
            { "能力冷却中", "Ability cooling down" },
            { "工具库存", "Tool stock" },
            { "建造进度", "Construction progress" },
            { "伤害", "Damage" },
            { "能力就绪", "Ability ready" },
            { "攻击可用", "Attack ready" },
            { "未知资源", "Unknown resource" },
            { "全局", "Global" },
            { "特殊能力可用", "Special ability ready" },
            { "施工进度", "Construction progress" },
            { "农田地块", "Farm plots" },
            { "关闭界面", "Close" },
        };
        private static readonly Regex matcher=new Regex(string.Join("|",translations.Keys.OrderByDescending(key=>key.Length).Select(Regex.Escape)),RegexOptions.Compiled|RegexOptions.CultureInvariant);
        public static bool IsEnglish(int preference,string gameLanguage,string systemLanguage)
        {
            if(preference==1)return false;if(preference==2)return true;
            string language=string.IsNullOrWhiteSpace(gameLanguage)?systemLanguage:gameLanguage;
            language=(language??"").Trim().ToLowerInvariant().Replace('_','-');
            return !(language=="zh"||language.StartsWith("zh-")||language.StartsWith("chinese"));
        }
        public static string Text(string text)=>Translate(text,English);
        private static string TranslateMatch(Match match)=>translations[match.Value];
        public static string Translate(string text,bool english)
        {if(string.IsNullOrEmpty(text)||!english)return text;return matcher.Replace(text,new MatchEvaluator(TranslateMatch));}
    }
}
