using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
namespace KingdomAdvisor
{
    // 显示适配器：领域标识、原生数据、旧配置键保持不变。
    public static class Localization
    {
        public static bool English {get;set;}=true;
        private static readonly Dictionary<string,string> translations=new Dictionary<string,string>(StringComparer.Ordinal)
        {
                        { "王国顾问", "Kingdom Advisor" },
            { "炸弹", "Bomb" },
            { "由工匠推动并由部队护送，用于炸毁悬崖洞穴。", "Pushed by builders and escorted by troops to destroy the cliff cave." },
            { "准备护送人员和金币；进入洞穴后的引爆与撤离以游戏交互提示为准。", "Prepare an escort and coins; follow the game's prompts for detonation and escape inside the cave." },
            { "炸弹出征旗", "Bomb expedition banner" },
            { "购买炸弹并组织部队护送，用于进攻悬崖洞穴。", "Purchase a bomb and assemble its escort to attack the cliff cave." },
            { "出征前准备工匠、军队和金币，确认护送路线安全。", "Prepare builders, troops and coins, and ensure the escort route is safe." },
            { "军队", "Army" },
            { "当前无升级交互", "No upgrade interaction available" },
            { "附近建筑详情", "Nearby building details" },
            { "狂战士", "Berserkers" }, { "待业平民", "Unassigned citizens" }, { "忍者", "Ninjas" }, { "渔夫", "Fishers" }, { "马厩管理员", "Stable keepers" },
            { "图鉴", "Catalog" },
            { "兴趣点", "Locations" },
            { "设置", "Settings" },
            { "地图", "Map" },
            { "岛屿记录", "Island journal" },
            { "资源", "Resources" },
            { "关闭", "Off" },
            { "开启", "On" },
            { "打开", "Open" },
            { "关闭面板", "Close panel" },
            { "顾问与提醒", "Advisor and alerts" },
            { "图鉴与进度", "Catalog and journal" },
            { "资源辅助", "Resource assistance" },
            { "移动与时间", "Movement and time" },
            { "手柄", "Controller" },
            { "键鼠", "Keyboard / mouse" },
            { "全部", "All" },
            { "防御", "Defense" },
            { "建设", "Construction" },
            { "经济", "Economy" },
            { "人口", "Population" },
            { "工具", "Tools" },
            { "航行", "Sailing" },
            { "科技", "Technology" },
            { "探索", "Exploration" },
            { "特殊", "Special" },
            { "环境", "Environment" },
            { "威胁", "Threat" },
            { "未分类", "Unclassified" },
            { "小地图", "Minimap" },
            { "地图背景", "Map background" },
            { "默认位置", "Default position" },
            { "顶部", "Top" },
            { "底部", "Bottom" },
            { "透明", "Transparent" },
            { "面板", "Panel" },
            { "情报范围", "Intel scope" },
            { "本次探索", "Explored this visit" },
            { "全岛", "Whole island" },
            { "树木", "Tree" },
            { "建筑", "Buildings" },
            { "营地与人口", "Camps and population" },
            { "敌人", "Enemies" },
            { "特殊地点", "Special locations" },
            { "王国顾问卡片", "Kingdom advisor" },
            { "Player 详情卡片", "Nearby details" },
            { "顾问背景", "Advisor background" },
            { "附近详情背景", "Nearby details background" },
            { "提醒背景", "Alert background" },
            { "主界面背景", "Main panel background" },
            { "人口与科技", "Population and technology" },
            { "用途与升级建议", "Uses and upgrade tips" },
            { "情境提醒", "Situational alerts" },
            { "防线风险提醒", "Defense alerts" },
            { "建设与招募缺口", "Staffing alerts" },
            { "坐骑能力状态", "Mount status" },
            { "图鉴图标", "Catalog icons" },
            { "岛屿进度记录", "Island journal" },
            { "字号", "Font size" },
            { "恢复卡片默认位置", "Reset HUD positions" },
            { "执行", "Apply" },
            { "无限钱袋容量", "Unlimited purse capacity" },
            { "手动添加资源", "Add resources manually" },
            { "地图长按传送", "Hold to teleport on map" },
            { "无限耐力", "Unlimited stamina" },
            { "游戏速度", "Game speed" },
            { "暂停", "Paused" },
            { "正常", "Normal" },
            { "2 倍", "2x" },
            { "4 倍", "4x" },
            { "常驻手柄光标", "Always show controller cursor" },
            { "光标速度", "Cursor speed" },
            { "慢", "Slow" },
            { "标准", "Standard" },
            { "快", "Fast" },
            { "很快", "Very fast" },
            { "呼出按键", "Panel button" },
            { "左摇杆按压 L3", "Left stick click (L3)" },
            { "右摇杆按压 R3", "Right stick click (R3)" },
            { "按下左摇杆", "Click left stick" },
            { "按下右摇杆", "Click right stick" },
            { "按下左摇杆短按面板", "Click left stick for panel" },
            { "删除", "Delete" },
            { "清空", "Clear" },
            { "完成", "Done" },
            { "自动", "Auto" },
            { "简体中文", "Simplified Chinese" },
            { "语言", "Language" },
            { "语言 / Language", "Language" },
            { "金币", "Coins" },
            { "宝石", "Gems" },
            { "骷髅", "Skulls" },
            { "灵魂", "Shades" },
            { "幽魂", "Shades" },
            { "工匠", "Builders" },
            { "弓手", "Archers" },
            { "弓箭手", "Archers" },
            { "骑士", "Knights" },
            { "农民", "Farmers" },
            { "游民", "Vagrants" },
            { "长枪兵", "Pikemen" },
            { "钱袋", "Purse" },
            { "坐骑", "Mount" },
            { "耐力", "Stamina" },
            { "饱食", "Fed" },
            { "疲劳", "Tired" },
            { "基础", "Basic" },
            { "中阶已解锁", "Stone technology unlocked" },
            { "高阶已解锁", "Iron technology unlocked" },
            { "中阶", "Stone" },
            { "高阶", "Iron" },
            { "建设科技", "Construction technology" },
            { "联机", "Online" },
            { "资源合计", "Total resources" },
            { "原生钱袋", "Native purse" },
            { "无限容量 · 数字钱袋", "Unlimited capacity · Numeric purse" },
            { "岛屿地图 ⇄", "Island map ⇄" },
            { "地图加载中…", "Loading map…" },
            { "可招募", "Recruitable" },
            { "营地", "Camps" },
            { "敌情未知", "Enemy data unavailable" },
            { "全岛 →", "Island →" },
            { "附近 →", "Nearby →" },
            { "附近交互", "Nearby interaction" },
            { "开启小地图", "Show minimap" },
            { "春季", "Spring" },
            { "夏季", "Summer" },
            { "秋季", "Autumn" },
            { "冬季", "Winter" },
            { "白昼", "Daytime" },
            { "夜晚", "Night" },
            { "上一页", "Prev" },
            { "下一页", "Next" },
            { "详情", "Details" },
            { "列表", "List" },
            { "上一地点", "Previous location" },
            { "下一地点", "Next location" },
            { "类别", "Category" },
            { "筛选", "Filter" },
            { "数量", "Amount" },
            { "快捷数量", "Preset amount" },
            { "玩家", "Player" },
            { "当前资源", "Selected resource" },
            { "仅金币", "Coins only" },
            { "全部钱袋资源", "All purse resources" },
            { "清空范围", "Clear scope" },
            { "清空所选资源", "Clear selected resources" },
            { "添加", "Add" },
            { "当前", "Current" },
            { "最近记录第", "Last recorded on day" },
            { "点击搜索 · 中文 / 英文", "Search · Chinese / English" },
            { "没有匹配条目。清空搜索或切换类别。", "No matching entries. Clear the search or change category." },
            { "当前筛选没有兴趣点。", "No points match this filter." },
            { "当前筛选没有地点。切换兴趣点分类或地图情报范围。", "No locations match this filter. Change category or map scope." },
            { "靠近建筑、工具或坐骑，查看用途与升级条件。", "Approach a building, tool or mount to see its purpose and upgrade requirements." },
            { "岛屿进度记录已关闭，可在设置中开启。", "Island journal is disabled. Enable it in Settings." },
            { "进入岛屿后自动记录已读取的情报。", "Observed information is recorded automatically after entering an island." },
            { "这是最近观察记录，离岛后不会实时更新。", "This is the last observation. It is not updated while you are away." },
            { "即时保存 · 玩法辅助默认关闭 · 单机与联机均开放", "Saved immediately · Gameplay assists off by default · Available offline and online" },
            { "上下选择，左右调整；数量可直接输入，范围 1–10000。只显示当前主题支持的资源。无限钱袋只扩充容量，需在资源辅助设置中开启。", "Navigate up/down, adjust left/right. Enter an amount from 1 to 10000. Only resources supported by this campaign are shown. Unlimited capacity is a separate option under Resource assistance." },
            { "手柄搜索 · 输入英文关键词；中文条目也可按类别浏览。", "Controller search · Enter English keywords, or browse by category." },
            { "上下选择 · 左右分类 · Enter 选择 · Tab 切页 · Esc 关闭", "Up/down: select · Left/right: category · Enter: confirm · Tab: tabs · Esc: close" },
            { "短按面板／长按显隐 · LB/RB 页签 · LT/RT", "Tap: panel / Hold: HUD · LB/RB: tabs · LT/RT:" },
            { "翻页 · 方向选择 · 确认／返回", "pages · D-pad: select · A/B: confirm/back" },
            { "右摇杆 · 光标 / 呼出键长按 · 显隐", "Right stick: cursor / Hold panel button: HUD" },
            { "页签", "tabs" },
            { "翻页", "pages" },
            { "方向选择", "D-pad: select" },
            { "确认／返回", "A/B: confirm/back" },
            { "短按面板／长按显隐", "Tap: panel / Hold: HUD" },
            { "升级条件", "Upgrade requirements" },
            { "升级目标", "Next upgrade" },
            { "本岛同类交互点", "Matching locations on this island" },
            { "费用、等级和锁定原因请靠近对象查看。不同主题以当前游戏数据为准。", "Approach an object for its cost, level and lock reason. Campaign-specific details come from the current game." },
            { "建议", "Tip" },
            { "费用", "Cost" },
            { "等级", "Level" },
            { "库存", "Stock" },
            { "耐久", "Health" },
            { "初始", "Initial" },
            { "驻防", "Garrison" },
            { "施工", "Building" },
            { "锁定", "Locked" },
            { "招募", "Recruit" },
            { "可交互", "Available" },
            { "暂不可用", "Unavailable" },
            { "已满", "Full" },
            { "已达容量", "At capacity" },
            { "处名称密集 · 切换附近查看", "labels overlap · Switch to Nearby" },
            { "秒 · 松开取消", "s · Release to cancel" },
            { "传送", "Teleport" },
            { "钱袋为空 · 留意收入与返程安全", "Purse empty · Watch your income and return route" },
            { "缺少工匠 · 建设和维修可能停滞", "No builders · Construction and repairs may stop" },
            { "夜间施工 · 先确认防线安全", "Night construction · Check your defenses first" },
            { "防线城墙已失守", "outer wall has fallen" },
            { "最外城墙耐久不足一半", "outer wall is below half health" },
            { "敌群接近最外城墙", "enemies are approaching the outer wall" },
            { "左侧", "Left" },
            { "右侧", "Right" },
            { "处工具库存为空", "tool stocks are empty" },
            { "处 · 缺少工匠", "sites · No builders" },
            { "单次数量为 1–10000", "Amount must be between 1 and 10000" },
            { "数量必须是 1–10000", "Amount must be between 1 and 10000" },
            { "本局未发现此资源类型", "This resource is not available in the current session" },
            { "地图传送尚未开启", "Map teleport is disabled" },
            { "请先进入存档", "Load a save first" },
            { "目标玩家不在本机控制范围", "This player is not controlled locally" },
            { "地点已变化，请重新选择", "The location changed. Select it again" },
            { "地面尚未加载", "Ground has not loaded yet" },
            { "此处不在已加载地面范围内", "This location is outside the loaded ground" },
            { "此地点靠近岛屿边界，无法验证安全落点", "Cannot verify a safe landing near the island boundary" },
            { "玩家移动组件不可用", "Player movement component is unavailable" },
            { "世界时间控制器尚未加载", "World time controller has not loaded yet" },
            { "已清空所选钱袋资源", "Selected purse resources cleared" },
            { "清空失败", "Clear failed" },
            { "已传送", "Teleported" },
            { "传送失败", "Teleport failed" },
            { "添加失败", "Add failed" },
            { "游戏实际处理结果", "Actual game result" },
            { "操作辅助出错，已关闭", "Assistance failed and was disabled" },
            { "手柄输入读取失败，请查看日志", "Controller input failed. Check the log" },
            { "人", " people" },
            { "只", " enemies" },
            { "处", " locations" },
            { "秒", "s" },
            { "天", " days" },
            { "岛", "Island" },
            { "第", "Day" },
            { "收起", "Hide" },
            { "城墙", "Wall" },
            { "塔楼", "Tower" },
            { "城堡／营地中心", "Castle / Camp center" },
            { "城堡", "Castle" },
            { "营地中心", "Camp center" },
            { "农舍", "Farmhouse" },
            { "农田", "Farm" },
            { "游民营地", "Vagrant camp" },
            { "难民营", "Vagrant camp" },
            { "市民之家", "Citizen house" },
            { "弓箭工具", "Bow stand" },
            { "工匠工具", "Builder tools" },
            { "农民工具", "Farmer tools" },
            { "长枪工具", "Pike stand" },
            { "盾牌／军队设施", "Shield / Army station" },
            { "忍者设施", "Ninja station" },
            { "锻造设施", "Forge" },
            { "工坊", "Workshop" },
            { "投石车", "Catapult" },
            { "弩炮设施", "Ballista" },
            { "面包设施", "Bakery" },
            { "灯塔", "Lighthouse" },
            { "码头", "Dock" },
            { "船只", "Boat" },
            { "船坞", "Shipyard" },
            { "传送设施", "Teleporter" },
            { "敌方传送门", "Enemy portal" },
            { "洞穴／山体据点", "Cave / Cliff stronghold" },
            { "科技设施", "Technology site" },
            { "雕像", "Statue" },
            { "纪念碑／特殊设施", "Monument / Special site" },
            { "隐士小屋", "Hermit cabin" },
            { "隐士", "Hermit" },
            { "宝箱", "Chest" },
            { "银行设施", "Bank" },
            { "商人", "Merchant" },
            { "浆果丛", "Berry bush" },
            { "马匹", "Horse" },
            { "狮鹫", "Griffin" },
            { "马厩", "Stable" },
            { "木马设施", "Trojan horse" },
            { "巨蛇相关设施", "Serpent site" },
            { "赫淮斯托斯设施", "Hephaestus site" },
            { "珀耳塞福涅设施", "Persephone site" },
            { "阿耳忒弥斯设施", "Artemis site" },
            { "雷神相关设施", "Thor site" },
            { "海拉相关设施", "Hel site" },
            { "宝石保管员", "Gem keeper" },
            { "宝石储存", "Gem storage" },
            { "边界设施", "Border site" },
            { "蛋", "Egg" },
            { "火焰桶", "Fire barrel" },
            { "货物", "Cargo" },
            { "君主墓地", "Ruler tomb" },
            { "蜡烛", "Candle" },
            { "王冠", "Crown" },
            { "召集铃", "Call bell" },
            { "飞行怪", "Floater" },
            { "贪婪怪", "Greedling" },
            { "巨型怪", "Breeder" },
            { "木制", "Wood" },
            { "石制", "Stone" },
            { "铁制", "Iron" },
            { "未建造", "Not built" },
            { "阻挡敌人，保护城内人员。", "Blocks enemies and protects people inside the walls." },
            { "升级会进入施工阶段；危险时段先确认防线仍能承受攻击。", "Upgrading starts construction. During dangerous hours, make sure your defenses can still withstand attacks." },
            { "提供驻守位置，协助防守附近区域。", "Provides garrison positions to defend the surrounding area." },
            { "不同等级与特殊改造用途不同；升级目标以当前对象为准。", "Levels and special upgrades serve different purposes. Check the actual object for its next upgrade." },
            { "提升王国建设阶段，解锁对应设施。", "Advances the kingdom's construction tier and unlocks facilities." },
            { "科技解锁与城堡等级是不同前置条件。", "Technology and castle level are separate requirements." },
            { "王国的中心，也是早期建设入口。", "The kingdom's center and its first construction site." },
            { "先稳定招募、工具和两侧防线，再向外扩张。", "Secure recruitment, tools and both defenses before expanding." },
            { "支持周边农田生产，升级后用途随主题和等级变化。", "Supports nearby farming. Upgraded behavior depends on the campaign and level." },
            { "需要农民和可用农田；冬季应留意收入来源。", "Requires farmers and usable farmland. Watch your sources of income in winter." },
            { "供农民耕作并产生收入。", "Allows farmers to grow crops and generate income." },
            { "建设后还需要人员；数量不等于正在生产的数量。", "Staff are needed after construction. The total count is not the number of productive sites." },
            { "招募新成员的来源。", "A source of new recruits." },
            { "扩张或清理附近森林前，留意营地是否会受到影响。", "Check whether expansion or nearby forest clearing will affect the camp." },
            { "可招募成为王国成员。", "Can be recruited into the kingdom." },
            { "招募后需要合适的工具才能从事对应职业。", "Recruits need the appropriate tools to take on a job." },
            { "提供招募人口的入口。", "Provides a place to recruit people." },
            { "费用及招募状态以实际对象为准。", "Check the actual object for its cost and recruitment status." },
            { "用于配置弓箭手，支持狩猎和防御。", "Equips archers for hunting and defense." },
            { "工具库存与已配置人员是两项不同统计。", "Tool stock and equipped workers are separate counts." },
            { "用于配置工匠，承担建造和维修。", "Equips builders for construction and repairs." },
            { "扩张前保证工匠能安全抵达施工位置。", "Make sure builders can reach construction sites safely before expanding." },
            { "用于配置农民，支持农田生产。", "Equips farmers to work the fields." },
            { "应同时检查可用农田与农民人数。", "Check both usable farmland and the number of farmers." },
            { "用于配置对应近战守卫。", "Equips the corresponding melee guards." },
            { "用途与可用性随主题变化。", "Purpose and availability vary by campaign." },
            { "用于军队相关配置或招募。", "Used to equip or recruit army units." },
            { "确认左右防线和军队配置后再投入资源。", "Check both defenses and army equipment before spending resources." },
            { "幕府主题的特殊人员设施。", "A special personnel facility in the Shogun campaign." },
            { "观察人员行为与当前防线需求。", "Watch the units' behavior and your current defense needs." },
            { "提供当前主题的装备或军队相关升级。", "Provides equipment or army upgrades for the current campaign." },
            { "具体购买结果以运行时升级目标为准。", "Check the actual upgrade target to see what a purchase provides." },
            { "生产防御或攻城相关设施。", "Produces defensive or siege equipment." },
            { "留意人员需求与设施移动到防线的时间。", "Allow for staffing requirements and travel time to the defenses." },
            { "支援防线的重型设施。", "Heavy equipment that supports the defenses." },
            { "建设与使用需要相应人员；保持移动路线安全。", "Building and operating it requires staff. Keep the travel route safe." },
            { "提供特殊防御能力。", "Provides specialized defensive capabilities." },
            { "特殊改造可能需要对应隐士。", "Special upgrades may require the corresponding hermit." },
            { "与吸引游民和人口补充有关。", "Helps attract vagrants and replenish the population." },
            { "关注消耗与实际招募结果。", "Monitor consumption and actual recruitment results." },
            { "改善岛屿航行相关设施。", "Improves facilities used for sailing between islands." },
            { "不同等级需要对应科技；先看升级前置条件。", "Different levels require appropriate technology. Check the requirements first." },
            { "船只与航行的交互位置。", "An interaction point for boats and sailing." },
            { "出航前检查人员、资源和当前岛屿防线。", "Check your crew, resources and island defenses before sailing." },
            { "用于岛屿间航行或当前主题的船队活动。", "Used for inter-island sailing or campaign-specific fleet activities." },
            { "施工、登船与出航是不同阶段。", "Construction, boarding and departure are separate stages." },
            { "与船只建造和船队有关。", "Related to boat construction and fleets." },
            { "费用和任务条件随战役变化。", "Costs and quest requirements vary by campaign." },
            { "用于快速移动或建立传送连接。", "Enables fast travel or a teleport connection." },
            { "先确认目的地安全与当前费用。", "Check the destination's safety and current cost first." },
            { "敌人相关的重要据点。", "An important enemy stronghold." },
            { "进攻前检查兵力、资源及反击风险。", "Check your forces, resources and counterattack risk before attacking." },
            { "战役推进相关的重要位置。", "An important location for campaign progress." },
            { "先确认当前战役的攻城条件。", "Check the current campaign's siege requirements first." },
            { "解锁更高阶段的建设科技。", "Unlocks a higher tier of construction technology." },
            { "金币支付与科技解锁不同于携带矿石材料。", "Paying coins and unlocking technology are separate from carrying ore materials." },
            { "解锁对应建设阶段。", "Unlocks the corresponding construction tier." },
            { "主题不同，设施名称与外观可能不同。", "The name and appearance can differ between campaigns." },
            { "提供增益、任务或特殊交互。", "Provides bonuses, quests or special interactions." },
            { "确认支付货币、持续状态和当前主题。", "Check the payment currency, active status and campaign." },
            { "与特殊能力、科技或任务有关。", "Related to special abilities, technology or quests." },
            { "先看实际锁定条件和支付结果。", "Check the actual lock requirements and payment result first." },
            { "与建筑特殊改造相关。", "Related to special building upgrades." },
            { "改造时可能需要带上对应隐士。", "An upgrade may require bringing the corresponding hermit." },
            { "特殊角色的解锁或招募入口。", "A place to unlock or recruit a special character." },
            { "解锁费用与后续改造费用需要分别考虑。", "Unlocking costs and later upgrade costs are separate." },
            { "提供资源或任务物品。", "Provides resources or quest items." },
            { "货币种类以当前对象为准。", "Check the actual object for the currency it uses." },
            { "与金币储存和经济管理有关。", "Related to coin storage and economic management." },
            { "钱袋金币与银行储存应分别理解。", "Coins in the purse and coins in the bank are separate." },
            { "提供主题相关的经济交互。", "Provides campaign-specific economic interactions." },
            { "观察当前费用与交付状态。", "Check the current cost and delivery status." },
            { "季节性经济资源。", "A seasonal source of income." },
            { "留意人员需求与当前季节。", "Watch staffing requirements and the current season." },
            { "可以付费砍伐，影响森林和可建设区域。", "Can be cut down for a fee, affecting the forest and buildable land." },
            { "砍树前检查附近游民营地与经济资源。", "Check nearby vagrant camps and income sources before cutting trees." },
            { "提供移动能力及主题相关特殊能力。", "Provides mobility and campaign-specific special abilities." },
            { "观察耐力、饱食和疲劳状态。", "Monitor stamina, feeding and exhaustion." },
            { "提供移动能力。", "Provides mobility." },
            { "奔跑消耗耐力；停留、步行和进食状态影响恢复。", "Running consumes stamina. Resting, walking and feeding affect recovery." },
            { "具有特殊能力的坐骑。", "A mount with special abilities." },
            { "能力可用性以当前玩家状态为准。", "Ability availability depends on the current player state." },
            { "与坐骑管理有关。", "Related to mount management." },
            { "具体容量与可用条件以当前对象为准。", "Check the actual object for its capacity and requirements." },
            { "奥林匹斯战役相关任务设施。", "A quest facility in the Call of Olympus campaign." },
            { "按实际缺少条件准备轮子、王冠等任务要素。", "Collect the missing quest items, such as wheels and crowns." },
            { "对应战役的特殊目标。", "A special objective in the corresponding campaign." },
            { "以当前任务和锁定提示为准。", "Follow the current quest and lock information." },
            { "奥林匹斯主题的特殊设施。", "A special facility in Call of Olympus." },
            { "查看当前任务条件和费用。", "Check the current quest requirements and cost." },
            { "查看任务条件与角色要求。", "Check the quest and character requirements." },
            { "北欧主题的特殊设施。", "A special facility in the Norse Lands campaign." },
            { "按当前任务提示操作。", "Follow the current quest instructions." },
            { "该对象尚未收录专属说明；费用和条件来自当前游戏。", "This object has no dedicated entry yet. Its costs and requirements come from the current game." },
            { "请以运行时提示为准。", "Follow the current game information." },
            { "与君主、能力或主题解锁有关。", "Related to rulers, abilities or campaign unlocks." },
            { "与宝石存取有关的交互入口。", "An interaction point for depositing or withdrawing gems." },
            { "管理当前战役中的宝石储存。", "Manages gem storage in the current campaign." },
            { "用于对应防御设施的消耗品。", "A consumable for the corresponding defensive facility." },
            { "钱袋持有和存放数量应分别理解。", "Resources carried in the purse and resources stored elsewhere are separate." },
            { "查看实际费用，出航前确认随行人员。", "Check the actual cost and confirm your crew before departure." },
            { "具体结果取决于当前战役。", "The result depends on the current campaign." },
            { "召集当前主题的相关人员或队伍。", "Calls the relevant personnel or teams for this campaign." },
            { "先确认防线与施工区域。", "Check your defenses and construction area first." },
            { "与王国扩张或对应主题的边界能力有关。", "Related to kingdom expansion or campaign-specific border abilities." },
            { "购买后还需要人员与相应设施。", "Staff and the appropriate facilities are still needed after purchase." },
            { "确认当前交互需要的货币。", "Check which currency this interaction requires." },
            { "条件已满足", "Requirements met" },
            { "当前没有可用升级", "No upgrade is currently available" },
            { "需要解锁对应的中阶建设科技", "Requires the corresponding stone construction technology" },
            { "需要解锁对应的高阶建设科技", "Requires the corresponding iron construction technology" },
            { "需要解锁或带上对应隐士", "Unlock or bring the corresponding hermit" },
            { "需要带上弩炮隐士", "Bring the ballista hermit" },
            { "需要带上面包师隐士", "Bring the baker hermit" },
            { "需要带上骑士隐士", "Bring the knight hermit" },
            { "需要带上马厩隐士", "Bring the stable hermit" },
            { "需要带上号角隐士", "Bring the horn hermit" },
            { "缺少所需金块", "Missing the required gold nuggets" },
            { "缺少木马轮子", "Missing Trojan horse wheels" },
            { "缺少木马所需王冠", "Missing crowns for the Trojan horse" },
            { "需要对应的火焰乘员", "Requires the corresponding fire crew member" },
            { "需要对应的珀耳塞福涅乘员", "Requires the corresponding Persephone crew member" },
            { "需要可用的船队船只", "Requires an available fleet boat" },
            { "已携带货物，需先处理现有货物", "Already carrying cargo. Handle it first" },
            { "巨蛇在门口，当前交互受阻", "The serpent blocks this interaction" },
            { "当前时机不允许；等待可用时段或冷却结束", "Unavailable now. Wait for the allowed time or cooldown" },
            { "当前区域不允许建设；检查王国边界和森林", "Cannot build here. Check kingdom borders and the forest" },
            { "对象暂时不可用；检查当前任务及施工状态", "Temporarily unavailable. Check the quest and construction status" },
            { "尚未解释的条件", "Unidentified requirement" },
            { "已解锁", "Unlocked" },
            { "能力冷却中", "Ability cooling down" },
            { "工具库存", "Tool stock" },
            { "建造进度", "Construction progress" },
            { "伤害", "Damage" },
            { "能力就绪", "Ability ready" },
            { "攻击可用", "Attack ready" },
            { "未知资源", "Unknown resource" },
            { "全局", "Global" },
            { "特殊能力可用", "Special ability ready" },
            { "施工进度", "Construction progress" },
            { "农田地块", "Farm plots" },
            { "关闭界面", "Close" },
        };
        private static readonly Regex matcher=new Regex(string.Join("|",translations.Keys.OrderByDescending(key=>key.Length).Select(Regex.Escape)),RegexOptions.Compiled|RegexOptions.CultureInvariant);
        public static bool IsEnglish(int preference,string gameLanguage,string systemLanguage)
        {
            if(preference==1)return false;if(preference==2)return true;
            string language=string.IsNullOrWhiteSpace(gameLanguage)?systemLanguage:gameLanguage;
            language=(language??"").Trim().ToLowerInvariant().Replace('_','-');
            return !(language=="zh"||language.StartsWith("zh-")||language.StartsWith("chinese"));
        }
        public static string Text(string text)=>Translate(text,English);
        private static string TranslateMatch(Match match)=>translations[match.Value];
        public static string Translate(string text,bool english)
        {if(string.IsNullOrEmpty(text)||!english)return text;return matcher.Replace(text,new MatchEvaluator(TranslateMatch));}
    }
}
